POPULATION_SIZE = 100
NUM_FEATURES = 7*7*3
NUM_REGISTERS = 8
MAX_INSTRUCTION_COUNT = 99
NUM_ACTIONS = range(3)
DISCOUNT_FACTOR = 0.99
POP_GAP = 0.50

DELETE_INSTRUCTION_PROBABILITY = 0.7
ADD_INSTRUCTION_PROBABILITY = 0.7
MUTATE_INSTRUCTION_PROBABILITY = 1.0
SWAP_INSTRUCTION_PROBABILITY = 1.0